# Generated by Django 6.0.5 on 2026-09-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Гость', max_length=50, verbose_name='Имя игрока')),
                ('score', models.IntegerField(verbose_name='Очки')),
                ('game', models.CharField(choices=[('memory', 'Memory Match'), ('quiz', 'English Quiz'), ('kitchen', 'Kitchen Rush')], max_length=20, verbose_name='Игра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рекорд',
                'verbose_name_plural': 'Рекорды',
                'ordering': ['-score'],
            },
        ),
    ]
